token = "TOKEN HERE"
clienttype = "bot" #'bot' is for bot accounts, 'user' is for user accounts (with the perms)
threadcount = 800 #Ammount of threads to use, You shouldnt need to change this.
changegameonlogin = True #True Changes the playing game on login.
logingame = "a Game" #Name of the name to play on login.
namechange = True #True to change name. Can sometimes glitch and not let anyone change the name.
servname = "New Server name here" #only required if the above is True
iconbegone = True #True removes icon. Do not use with chnage icon enabled also.
changeicon = False #True Changes icon to a file specified below.
iconfile = 'guy.jpg' #Put the image in the "serversmasher" folder
chandel = True #True deletes all channels
roledel = True #True deletes all roles underneath the bots role
userban = False #True bans all members, except the ones below. you can add as many as you like.
banreason = "DEADBREADS RAID TOOLBOX"
userid = ['user#3981','user#7579']
senddm = True #True sends everyone a DM, specified below.
dmcontent = "Custom DM Here"
createchan = True #True creates channels, using the method below
chanmethod = "set" #'ascii' for random ascii name, 'set' for set name below, 'voice' for a voice channel with the name below(If voice and channel deletion is enabled you will not be able to use spam methods).
channame = "Channel Name here" #Name of the channels to create
channelno = "70" #ammount of channels, the limit for discord is 500
usespam = True #True enables spam after everything is complete.
spammethod = "everyone" #"massment" for mass mention, "asc" for random ascii spam, "text" for custom text spam, everyone for fast @everyone spam.
usetts = "false" #(true or false), for the spam.
customtxt = "custom text here" #only if you use text spam method
gimmieadmin = False #True Gives you an admin role.
me = 'your ID here' #put your client ID here if you enable gimmieadmin
giveeveryoneadmin = True #True gives @everyone admin. Works best if you dont ban them ¯\_(ツ)_/¯

