token = "Token Here"
clienttype = "bot" #'bot' is for bot accounts, 'user' is for user accounts (with the perms)
namechange = False #True to change name. Can sometimes glitch and not let anyone change the name.
servname = "Server Name here" #only required if the above is True
iconbegone = False #True removes icon. Do not use with chnage icon enabled also.
changeicon = False #True Changes icon to a file specified below.
iconfile = 'meme.jpg' #Put the image in the "serversmasher" folder
chandel = False #True deletes all channels
roledel = False #True deletes all roles underneath the bots role
userban = False #True bans all members, except the ones below. you can add as many as you like.
userid = ['user#0000','user#0000']
senddm = False #True sends everyone a DM, specified below.
dmcontent = "DM Content here"
createchan = False #True creates channels, using the method below
chanmethod = "set" #'ascii' for random ascii name, 'set' for set name below
channame = "channel name here" #Name of the channels to create
channelno = "30" #ammount of channels, the limit for discord is 500
spammethod = "text" #"massment" for mass mention, "asc" for random ascii spam, "text" for custom text spam
customtxt = "Spam text here" #only if you use text spam method
gimmieadmin = False #True Gives you an admin role.
giveeveryoneadmin = False #True gives everyone admin. Works best if you dont ban them ¯\_(ツ)_/¯
me = 'Your client id here' #put your client ID here if you enable gimmieadmin
